export interface Product {
    _id?: number | string;
    name: string;
    thumbnail: string;
    images: string[];
    description: string;
    brand: string;
    materials: string[];
    color?: string;
    size?: string;
    gender: string;
    category: string;
    subCategory: string;
    moq?: number;
    slug?: string;
    price?: number;
    discountPrice?: number;
    costPrice?: number;
    stock?: number;
    sku?: string;
    weight?: number;
    dimentions?: string;
    tags?: string[];
    warranty?: string;
    returnPolicy?: string;
    metaTitle?: string;
    metaDescription?: string;
    active?: boolean;
    featured?: boolean;
}